# exception-handling-in-python-1
exception handling
